# The Site Configuration

theme: jekyll-theme-chirpy

lang: en
timezone: America/New_York

# jekyll-seo-tag settings
title: Mohamed Fadlalla
tagline: Software Engineer at Google | Indie Hacker
description: >-
  The engineering blog and portfolio of Mohamed Fadlalla. Writing about System Design, Cloud-Native Architecture, and building high-performance SaaS tools.

url: "https://mofadlalla.io"

github:
  username: mofadlalla

twitter:
  username: mofadlalla

social:
  name: Mohamed Fadlalla
  email: mofadlalla10@gmail.com
  links:
    - https://twitter.com/mofadlalla
    - https://github.com/mofadlalla
    - https://linkedin.com/in/mofadlalla

# Web Analytics Settings
analytics:
  umami:
    id: "8fc720d0-5da8-40fd-a1e9-2713fb0735ee"
    domain: "https://cloud.umami.is"

# Prefer color scheme setting (empty = system default with toggle)
theme_mode:

# The avatar on sidebar
avatar: "https://github.com/mofadlalla.png"

# Global switch for TOC in posts
toc: true

paginate: 10

baseurl: ""

# ------------ Chirpy Core Options ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Jekyll Admin
jekyll_admin:
  homepage: "posts"
